# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    container_name: postgresDB
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
